language: node_js
node_js: 9
os: linux
install:
  - npm install
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
jobs:
  include:
  - stage: Check
    script:
    - ./tools/check_signed_off.sh --travis
    - npm run travis-lint
  - stage: Build
    script:
    - npm install
    - npm run build
  - stage: Deploy
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: dist
      on:
        branch: master
        condition: $VERSION = 0
    script:
      - "if ! test -d dist; then npm install && npm run build; fi"
      - npm run check-version && VERSION=$?
